#!/bin/sh

# $1 = data to backup
# $2 = backup dir

SRC="${1}"
BACKUPDIR="${2}"

[ ! -d "${SRC}" ] && {
	printf -- "[-] source dir not found (%s) ... exiting ....\n" "${SRC}"
    exit 1
}


[ ! -d "${BACKUPDIR}" ] && {
    prinntf -- "[-] BACKUPDIR not found (%s) ... exiting ....\n" "${BACKUPDIR}"
    exit 1
}


printf -- "[+] backup %s -> %s\n"  "${SRC}" "${BACKUPDIR}"


